version: 0.1.{build}
image: Visual Studio 2019
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
deploy:
  provider: NuGet
  server:
  api_key:
    secure: AyJMm45JtIDHVRZUuTT+C3NPLkPOsRHV33uYRg7pUBNoH4pz8/xPtA0KAnWKJU5E
  skip_symbols: false
  symbol_server:
  artifact: /.*\.nupkg/
build_script:
  - ps: dotnet build -c Release
test_script:
  - ps: pushd tests\ClamNet.Client.UnitTests; dotnet test; popd
artifacts:
  - path: src\ClamNet.Client\bin\Release\*.nupkg